camera:
   alt: 3500 # camera alt (ft)
   lat: "35.751253" # can be decimal int, string, or degrees copied from Google Maps (format 35°45'31.2"N or 78°53'59.5"W)
   long: "-78.902028"
drone:
    length: 3 # y drone (in feet)
    width: 4 # x
    depth: 5 # z
scale: # at 1x zoom
    dist: 10 # at 10 feet away from the camera...
    width: 10 # its viewing angle is 10 feet wide