camera:
  alt: 85.763 # camera alt (meters above sea level)
  lat: "35.727481" # can be decimal int, string, or degrees copied from Google Maps (format 35  45'31.2"N or 78  53'59.5"W)
  long: "-78.695925"
  offset: 51.733814668 #-32.5  # the offset in degrees from north (facing west would be 90, south 180, and east 270)
  deactivate_pos:  # This example will make the camera look straight down without panning it.
    pan: 0 # the pan to go to when the camera deactivates (0 is no pan change)
    tilt: -90 # the tilt to go to when the camera deactivates (0 is no tilt change)
in  min_zoom_step: 2000 # the minimum change in zoom to update the ptz in pan steps, which run from 0 to 9999 linearly
  delay: 10 # the delay after the activate_method detects a deactivation for the camera to stop recording.
  maximum_zoom: 31 # the maximum zoom of the camera (31x for the Q8615-e I'm using)
  zoom_error: 1.2 # the amount of error (1.2 would be 20% extra FOV, 0.8 would be 20% less)
  lead: 0 # The number of seconds to lead the drone by
  store_recordings: "recordings"  # The path to store the recordings in
drone:
  x: 3 # size (in meters, relative to front of drone)
  y: 4
  z: 5
scale: # at 1x zoom
  dist: 0.7239 # at x meters away from the camera... (calculated for q8615-e)
  width: 0.889 # its viewing angle is x meters wide
camera_login:
  ip: "192.168.60.101" # the ip of the camera
  username: "" # the username of the camera
  password: "" # the password of the camera
kafka:
  ip: "192.168.60.202:9092"
  data_topic: "dronetracker-data"
  command_topic: "dronetracker-command"
  hz: 10
experiment:
  stop_recording_after: 5  # After <x> seconds from the last packet sent in Kafka to kafka/data_topic, stop recording and deactivate
logs: "debug" # "debug", "info", "warning" or "error"



