camera:
   alt: 400 # camera alt (meters)
   lat: "35.751253" # can be decimal int, string, or degrees copied from Google Maps (format 35°45'31.2"N or 78°53'59.5"W)
   long: "-78.902028"
   radius_activate: 0 # an int/float containing the horizontal (top-down) meter radius for the camera to start recording and moving
drone:
    x: 3 # (in meters, relative to front of drone)
    y: 4
    z: 5
scale: # at 1x zoom
    dist: 10 # at 10 meters away from the camera...
    width: 10 # its viewing angle is 10 meters wide
login:
    ip: "an example ip" # the ip of the camera
    username: "johndoe" # the username of the camera
    password: "p@$$w0rd" # the password of the camera
