camera:
  alt: 400 # camera alt (meters)
  lat: "35.751253" # can be decimal int, string, or degrees copied from Google Maps (format 35°45'31.2"N or 78°53'59.5"W)
  long: "-78.902028"
  radius_activate: 0 # an int/float containing the horizontal (top-down) meter radius for the camera to start recording and moving
  offset: 0  # the offset in degrees from north (facing west would be 90, south 180, and east 270)
  deactivate_pos:  # This example will make the camera look straight down without panning it.
    pan: 0 # the pan to go to when the camera deactivates (0 is no pan change)
    tilt: -90 # the tilt to go to when the camera deactivates (0 is no pan change)
  min_step: 0 # the minimum distance from the (pan or tilt) to update the camera's ptz. For example, a value of 1 would move the camera any time the pan or tilt differed by at least 1 degree.
  wait: 0 # the time to wait before checking for updates. This mainly has an effect on CPU usage.
drone:
  address: "tcp:localhost:5763"
  x: 3 # (in meters, relative to front of drone)
  y: 4
  z: 5
scale: # at 1x zoom
  dist: 10 # at 10 meters away from the camera...
  width: 10 # its viewing angle is 10 meters wide
login:
  ip: "1.1.1.1" # the ip of the camera
  username: "johndoe" # the username of the camera
  password: "p@$$w0rd" # the password of the camera
debug: 1  # the log level. 0 is off. 1 is normal. 2 is all logs.
