services:
  dronetracker:
    image: dronetracker-aerpaw:latest
    volumes:
      - recording_storage:/opt/DroneTracker/recordings
    container_name: dronetracker
    build:
      context: .
      network: host
    privileged: true
    network_mode: 'host'
volumes:
  recording_storage:
    driver: local
    driver_opts:
      type: none
      device: /opt/DroneTracker/recordings
networks:
  app:
    driver: bridge
  outer-world:
    ipam:
      driver: default
