version: '3.10'

services:
  dronetracker:
    image: dronetracker-aerpaw:latest
    container_name: dronetracker
    build:
      context: .
      network: host
    privileged: true
    network_mode: 'host'
networks:
  app:
    driver: bridge
  outer-world:
    ipam:
      driver: default
