version: '3.10'

services:
  cameradistance:
    image: cameradist-aerpaw:latest
    build:
      context: .
      network: host
    privileged: true
    networks:
    - app
    - outer-world
networks:
  app:
    driver: bridge
  outer-world:
    ipam:
      driver: default
